apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-pipeline-agent.fullname" . }}
  labels:
    {{- include "azure-pipeline-agent.labels" . | nindent 4 }}
data:
  pat: {{ required "A personal access token (PAT) is required!" .Values.pipeline.pat | b64enc }}
