{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "azure-pipeline-agent.serviceAccountName" . }}
  labels:
{{ include "azure-pipeline-agent.labels" . | nindent 4 }}
{{- end -}}
